### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by dungwinux** [taptapking/2048#9]
- Version: 4.2.1 (441ae9642)
- OS: Antergos Linux x86_64
- Terminal: Konsole
- Description: The text blinks black and white at the start of the game. It disappears when hit 1 (use dark theme) or 2 (use light theme) in User preferences

**Comment by dungwinux** [comment]
![2018-06-20 20-52-51](https://user-images.githubusercontent.com/23451424/41662986-902a3094-74cc-11e8-857a-2d226387cba4.gif)

**Comment by NOVAglow** [comment]
This is because of the `LowVideo` call at line 901 ([reference](https://github.com/taptapking/2048/blob/master/2048.pas#L901)).

Khoa said he put this for colors to display properly. If it displays properly on his machine, but not us GNU/Linux machines, we probably need some sort of compiler directive to resolve this problem.

**Comment by dungwinux** [comment]
Okay, I believe that can be fixed soon, but, it means that there's another problem. It seems like the `LowVideo` is not working (or reseted) after changing theme in program.

**Comment by NOVAglow** [comment]
I don't see if `LowVideo` is a visible change man. I see no difference. Probably for old computers.

**Comment by dungwinux** [comment]
I just check and it seems like problem's still there in version 5.0
